services:
  gitlab-runner:
    build: .
    container_name: gitlab-runner
    privileged: true
    restart: always
    volumes:
      - ./ssh:/root/.ssh
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
