concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Docker Unix Runner"
  url = "https://gitlab.com/"
  id = 49502402
  token = "glrt-1KtKzrsrdzUc43DioXJrMG86MQpwOjE2dHdlNwp0OjMKdTpoZmEzbBg.01.1j0tbwura"
  token_obtained_at = 2025-08-15T14:26:04Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.9.2-eclipse-temurin-17"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
